import { Notice } from 'obsidian';

import PDFPlus from 'main';
import { PDFPlusComponent } from 'lib/component';
import { PDFViewerChild } from 'typings';
import { PDFViewerDrafts } from './drafts';
import { patchTextboxResizing } from './resize';


/** Values of pdf.js' `AnnotationEditorType` used here. */
const EDITOR_MODE_NONE = 0;
const EDITOR_MODE_FREETEXT = 3;

/** Value of pdf.js' `AnnotationEditorParamsType.FREETEXT_SIZE`. */
const PARAM_FREETEXT_SIZE = 11;

/** How long to wait for pdf.js to switch the editor mode. */
const MODE_SWITCH_TIMEOUT_MS = 2000;

/** The parts of pdf.js' annotation editor API used here. pdf-dist doesn't type them. */
interface EditorLayer {
    div: HTMLElement;
    createAndAddNewEditor(point: { offsetX: number, offsetY: number }, isCentered: boolean): TextEditor | null;
}

interface UIManager {
    hasSelection: boolean;
    getActive(): TextEditor | null;
    getEditors(pageIndex: number): TextEditor[];
    isSelected(editor: TextEditor): boolean;
    updateParams(type: number, value: unknown): void;
}

interface TextEditor {
    x: number;
    y: number;
    parent: EditorLayer | null;
    parentDimensions: [number, number];
    div: HTMLElement;
    editorDiv?: HTMLElement;
    /** While false, pdf.js ignores focusin/focusout of the editor. */
    _focusEventsAllowed: boolean;
    isInEditMode(): boolean;
    enableEditMode(): void;
    commitOrRemove(): void;
    updateParams(type: number, value: unknown): void;
    getInitialTranslation(): [number, number];
    translate(x: number, y: number): void;
}

/** The text boxes a font size chosen in the toolbar applies to. */
export interface FontSizeTarget {
    /** The text box being typed into, and the caret in it. */
    editing: TextEditor | null;
    range: Range | null;
    selected: TextEditor[];
}

/**
 * Text box tool of one PDF viewer: click on a page to place a text box and type.
 *
 * Uses pdf.js' own FreeText editor, which Obsidian ships but doesn't use. The text boxes
 * are saved as FreeText annotations with an appearance stream generated by pdf.js, so they
 * show up in other PDF viewers and can be edited again later.
 *
 * Unsaved text boxes are registered as drafts with the write coordinator, so every write to
 * the file includes them. They are also saved when the tool is turned off and when the viewer
 * is closed.
 */
export class TextboxTool extends PDFPlusComponent {
    static BUTTON_CLS = 'pdf-plus-textbox-button';
    static FONT_SIZE_CLS = 'pdf-plus-textbox-font-size';
    static FONT_SIZES = [6, 8, 10, 12, 14, 16, 18, 20, 24, 28, 32, 36, 48];
    static MIN_FONT_SIZE = 1;
    static MAX_FONT_SIZE = 200;
    /** Font size of new text boxes, shared by all viewers like pdf.js' own default. */
    static defaultFontSize = 10;

    /** Round to an integer within the allowed range. */
    static clampFontSize(size: number) {
        return Math.min(TextboxTool.MAX_FONT_SIZE, Math.max(TextboxTool.MIN_FONT_SIZE, Math.round(size)));
    }

    child: PDFViewerChild;
    drafts: PDFViewerDrafts;
    active = false;
    /** Font size of the selected text box, or of new ones if none is selected. */
    fontSize = TextboxTool.defaultFontSize;
    /** Whether the current pointer gesture started inside a text box. */
    private gestureInTextbox = false;
    /** Stops keeping the caret, see keepCaret(). */
    private releaseCaret: (() => void) | null = null;

    constructor(plugin: PDFPlus, child: PDFViewerChild) {
        super(plugin);
        this.child = child;
        this.drafts = new PDFViewerDrafts(plugin.lib, child);
    }

    onload() {
        patchTextboxResizing(this.plugin);

        // Capture phase: runs before pdf.js' handlers and before the event reaches the text layer.
        this.registerDomEvent(this.child.containerEl, 'pointerdown', (evt) => {
            const target = evt.target as HTMLElement | null;
            this.gestureInTextbox = typeof target?.closest === 'function' && !!target.closest('.freeTextEditor');
        }, true);
        this.registerDomEvent(this.child.containerEl, 'pointerup', (evt) => this.onPointerUp(evt), true);
        this.registerDomEvent(this.child.containerEl, 'keydown', (evt) => {
            // In a text box, pdf.js handles Escape itself (it ends editing). Outside, it ends the tool.
            if (evt.key === 'Escape' && this.active && !this.activeEditor()) {
                this.deactivate();
            }
        });

        const eventBus = this.child.pdfViewer?.eventBus;
        if (eventBus) {
            // Dispatched when a text box is selected, with its properties.
            this.lib.registerPDFEvent('annotationeditorparamschanged', eventBus, this, ({ details }) => {
                const size = details.find(([type]) => type === PARAM_FREETEXT_SIZE)?.[1];
                if (typeof size === 'number') this.showFontSize(size);
            });
            this.lib.registerPDFEvent('annotationeditorstateschanged', eventBus, this, ({ details }) => {
                if (details.hasSelectedEditor === false) this.showFontSize(TextboxTool.defaultFontSize);
            });
        }
    }

    onunload() {
        this.releaseCaret?.();
        // Called from PDFViewerChild.unload() before the viewer is torn down, so the document
        // is still alive. `drafts.save()` captures the drafts synchronously before its first await.
        this.drafts.save()
            .catch((err) => {
                console.error(err);
                new Notice(`${this.plugin.manifest.name}: Failed to save text boxes: ${err.message}`);
            })
            .finally(() => this.drafts.dispose());
        this.setActive(false);
    }

    get pdfViewer(): any {
        return this.child.pdfViewer?.pdfViewer;
    }

    private get uiManager(): UIManager | null {
        return this.pdfViewer?._layerProperties?.annotationEditorUIManager ?? null;
    }

    async toggle() {
        if (this.active) await this.deactivate();
        else await this.activate();
    }

    async activate(): Promise<boolean> {
        if (this.active) return true;

        if (!this.lib.isEditable(this.child)) {
            new Notice(`${this.plugin.manifest.name}: Text boxes require "Enable PDF editing" in the settings, and the PDF must be inside the vault.`);
            return false;
        }

        const pdfViewer = this.pdfViewer;
        if (!pdfViewer?.pdfDocument) return false;

        // The setter doesn't wait for the (async) mode switch; createAndAddNewEditor() returns
        // null until the new mode has reached the editor layers.
        pdfViewer.annotationEditorMode = { mode: EDITOR_MODE_FREETEXT };
        if (!await this.waitForMode(EDITOR_MODE_FREETEXT)) {
            new Notice(`${this.plugin.manifest.name}: Failed to start the text box tool.`);
            return false;
        }

        // pdf.js' default is global, but may have been reset by a new pdf.js instance.
        const uiManager = this.uiManager;
        if (uiManager && !uiManager.hasSelection) uiManager.updateParams(PARAM_FREETEXT_SIZE, TextboxTool.defaultFontSize);
        this.showFontSize(TextboxTool.defaultFontSize);

        this.setActive(true);
        return true;
    }

    /**
     * The text boxes a font size chosen in the toolbar applies to. Capture it before the toolbar
     * takes the focus (which ends the edit mode of the text box being typed into): a click
     * elsewhere can change the selection before the size is applied.
     */
    captureFontSizeTarget(): FontSizeTarget {
        const editing = this.activeEditor();
        let range: Range | null = null;
        if (editing?.editorDiv) {
            const selection = editing.editorDiv.ownerDocument.getSelection();
            if (selection?.rangeCount && editing.editorDiv.contains(selection.anchorNode)) {
                range = selection.getRangeAt(0).cloneRange();
            }
        }
        return { editing, range, selected: this.selectedEditors() };
    }

    /**
     * Set the font size of the target's text boxes (by default the selected ones) and of new
     * ones. Unless `returnFocus` is false, the text box that was being typed into gets the focus
     * back.
     */
    setFontSize(size: number, target = this.captureFontSizeTarget(), returnFocus = true) {
        const uiManager = this.uiManager;
        if (!uiManager) return;

        const selected = this.selectedEditors();
        const editors = target.selected.filter((editor) => editor.parent);
        const selectionKept = editors.length === selected.length && editors.every((editor) => selected.includes(editor));
        if (selectionKept) {
            // Changes the selected text boxes, or pdf.js' default if none is selected.
            uiManager.updateParams(PARAM_FREETEXT_SIZE, size);
            this.showFontSize(size);
        } else {
            // The selection has changed, e.g. by a click on another text box, which also ends
            // the input in the toolbar. Leave the newly selected text boxes alone.
            for (const editor of editors) editor.updateParams(PARAM_FREETEXT_SIZE, size);
        }
        const editor = editors[0] ?? selected[0];
        if (editor) {
            (editor.constructor as unknown as { updateDefaultParams(type: number, value: unknown): void })
                .updateDefaultParams(PARAM_FREETEXT_SIZE, size);
        }
        TextboxTool.defaultFontSize = size;

        if (returnFocus && selectionKept) this.returnFocus(target);
    }

    /**
     * Start entering a font size in the toolbar. Call it before the input takes the focus.
     *
     * Keeps the text box being typed into in edit mode while the input has the focus, like
     * pdf.js does while the window is in the background. Otherwise pdf.js commits the text box
     * on focusout, and FreeTextEditor.disableEditMode() takes the focus back from the input.
     */
    beginFontSizeInput(): FontSizeTarget {
        const target = this.captureFontSizeTarget();
        if (target.editing) target.editing._focusEventsAllowed = false;
        return target;
    }

    /**
     * End entering a font size in the toolbar: return the focus to the text box that was being
     * typed into, or finish it like its focusout would have.
     */
    endFontSizeInput(target: FontSizeTarget, returnFocus: boolean) {
        const { editing } = target;
        if (!editing) return;

        if (returnFocus && editing.parent) {
            // pdf.js ignores this focusin: the text box is still selected and in edit mode.
            this.returnFocus(target);
            editing._focusEventsAllowed = true;
            return;
        }

        editing._focusEventsAllowed = true;
        if (editing.parent && editing.isInEditMode()) {
            // Leave the focus where it went: FreeTextEditor.disableEditMode() focuses the text box.
            const div = editing.div;
            div.focus = () => {};
            try {
                editing.commitOrRemove();
            } finally {
                Reflect.deleteProperty(div, 'focus');
            }
        }
    }

    /** Put the text box that was being typed into back into edit mode, with the caret where it was. */
    private returnFocus({ editing, range }: FontSizeTarget) {
        const editorDiv = editing?.editorDiv;
        if (!editing?.parent || !editorDiv) return;
        // The toolbar buttons don't take the focus.
        if (editorDiv.ownerDocument.activeElement !== editorDiv) {
            if (!editing.isInEditMode()) editing.enableEditMode();
            editorDiv.focus();
            if (range && editorDiv.contains(range.startContainer) && editorDiv.contains(range.endContainer)) {
                const selection = editorDiv.ownerDocument.getSelection();
                selection?.removeAllRanges();
                selection?.addRange(range);
            }
        }
        this.keepCaret(editorDiv);
    }

    /**
     * Keep the caret in the text box where it is now, until the user types or clicks.
     *
     * A new font size moves the text box, and pdf.js then moves its element in the DOM to keep
     * the reading order (AnnotationEditorLayer.moveEditorInDOM, in a timeout; with more than one
     * text box on the page, the element is always reinserted). That takes the focus from the
     * text box. pdf.js focuses it again, but with the caret at the start.
     */
    private keepCaret(editorDiv: HTMLElement) {
        this.releaseCaret?.();
        const doc = editorDiv.ownerDocument;
        const selection = doc.getSelection();
        if (!selection?.rangeCount) return;
        // Not the Range itself: it collapses when its nodes leave the DOM.
        const { startContainer, startOffset, endContainer, endOffset } = selection.getRangeAt(0);
        if (!editorDiv.contains(startContainer) || !editorDiv.contains(endContainer)) return;

        const restore = () => {
            if (!editorDiv.contains(startContainer) || !editorDiv.contains(endContainer)) return;
            doc.getSelection()?.setBaseAndExtent(startContainer, startOffset, endContainer, endOffset);
        };
        const win = doc.win;
        const release = () => {
            editorDiv.removeEventListener('focus', restore);
            win.removeEventListener('keydown', release, true);
            win.removeEventListener('pointerdown', release, true);
            if (this.releaseCaret === release) this.releaseCaret = null;
        };
        editorDiv.addEventListener('focus', restore);
        win.addEventListener('keydown', release, true);
        win.addEventListener('pointerdown', release, true);
        this.releaseCaret = release;
    }

    private selectedEditors(): TextEditor[] {
        const uiManager = this.uiManager;
        const pagesCount: number = this.pdfViewer?.pagesCount ?? 0;
        const editors: TextEditor[] = [];
        if (!uiManager) return editors;
        for (let pageIndex = 0; pageIndex < pagesCount; pageIndex++) {
            for (const editor of uiManager.getEditors(pageIndex)) {
                if (uiManager.isSelected(editor)) editors.push(editor);
            }
        }
        return editors;
    }

    private showFontSize(size: number) {
        this.fontSize = size;
        const el = this.child.toolbar?.toolbarLeftEl.querySelector('.' + TextboxTool.FONT_SIZE_CLS + ' .pdf-plus-textbox-font-size-value');
        // Don't overwrite a size being typed (e.g. when a click on another text box selects it
        // before the input loses the focus); the input shows the current size when it's done.
        if (el instanceof HTMLInputElement && el.ownerDocument.activeElement !== el) el.value = String(size);
    }

    /** Turn the tool off and save the text boxes. */
    async deactivate() {
        if (!this.active) return;

        this.commitActiveEditor();
        const pdfViewer = this.pdfViewer;
        if (pdfViewer) pdfViewer.annotationEditorMode = { mode: EDITOR_MODE_NONE };
        this.setActive(false);

        await this.save();
    }

    async save() {
        try {
            await this.drafts.save();
        } catch (err) {
            console.error(err);
            new Notice(`${this.plugin.manifest.name}: Failed to save text boxes: ${err.message}`);
        }
    }

    private setActive(active: boolean) {
        this.active = active;
        this.child.containerEl.toggleClass('pdf-plus-textbox-active', active);
        this.child.toolbar?.toolbarLeftEl.querySelector('.' + TextboxTool.BUTTON_CLS)?.toggleClass('is-active', active);
        this.child.toolbar?.toolbarLeftEl.querySelector<HTMLElement>('.' + TextboxTool.FONT_SIZE_CLS)?.toggle(active);
    }

    private async waitForMode(mode: number) {
        const start = Date.now();
        while (Date.now() - start < MODE_SWITCH_TIMEOUT_MS) {
            const pdfViewer = this.pdfViewer;
            if (pdfViewer?.annotationEditorMode === mode && this.layerOf(pdfViewer.currentPageNumber)) return true;
            await new Promise((resolve) => window.setTimeout(resolve, 30));
        }
        return false;
    }

    private layerOf(pageNumber: number): EditorLayer | null {
        return this.pdfViewer?.getPageView(pageNumber - 1)?.annotationEditorLayer?.annotationEditorLayer ?? null;
    }

    /** The editor being typed into, if any. */
    private activeEditor(): TextEditor | null {
        const editor = this.uiManager?.getActive();
        return editor?.isInEditMode() ? editor : null;
    }

    private commitActiveEditor() {
        const editor = this.activeEditor();
        // Committing must come before leaving edit mode: commit() returns early outside of it.
        // An editor without parent has been removed already. Empty ones must be removed rather
        // than committed: commit() moves the focus, pdf.js then removes the empty editor itself,
        // and commit() fails halfway.
        if (editor?.parent) editor.commitOrRemove();
    }

    private onPointerUp(evt: PointerEvent) {
        if (!this.active || evt.button !== 0) return;

        // Gestures that start in a text box are pdf.js' business (caret, double-click, dragging),
        // wherever they end: on a double-click, pdf.js hides the text box's overlay on the second
        // pointerdown, so the pointerup lands on the canvas below.
        if (this.gestureInTextbox) return;

        const target = evt.target as HTMLElement | null;
        if (typeof target?.closest !== 'function') return;
        if (target.closest('.freeTextEditor')) return;

        const pageEl = target.closest<HTMLElement>('.page[data-page-number]');
        if (!pageEl) return;
        const layer = this.layerOf(Number(pageEl.dataset.pageNumber));
        if (!layer) return;

        // Finish the text box being typed into; the click still places a new one.
        this.commitActiveEditor();

        const rect = layer.div.getBoundingClientRect();
        const point = { offsetX: evt.clientX - rect.left, offsetY: evt.clientY - rect.top };
        const editor = layer.createAndAddNewEditor(point, false);
        if (!editor) return;

        fixPosition(editor, point);
        editor.enableEditMode();
        editor.editorDiv?.focus();
    }
}

/**
 * pdf.js reads `--freetext-padding` once per window (`AnnotationEditorLayer._initialized`),
 * when the first editor layer is created. If our stylesheet wasn't loaded yet at that time,
 * `FreeTextEditor._internalPadding` stays NaN for good, and every text box gets x = y = NaN:
 * no position on screen, and a broken /Rect in the file.
 *
 * Fix the padding and place the editor again. Don't remove and recreate it instead: that
 * triggers focusout -> commitOrRemove asynchronously, which then hits the new editor.
 */
function fixPosition(editor: TextEditor, point: { offsetX: number, offsetY: number }) {
    const editorClass = editor.constructor as unknown as { _internalPadding: number };
    if (!Number.isNaN(editor.x) && !Number.isNaN(editorClass._internalPadding)) return;

    const padding = parseFloat(getComputedStyle(editor.parent?.div ?? document.documentElement).getPropertyValue('--freetext-padding'));
    editorClass._internalPadding = Number.isNaN(padding) ? 2 : padding;

    const [width, height] = editor.parentDimensions;
    editor.x = point.offsetX / width;
    editor.y = point.offsetY / height;
    editor.translate(...editor.getInitialTranslation()); // calls fixAndSetPosition() -> left/top
}
